# Generated by Django 4.0.4 on 2022-05-28 09:39

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('address', models.CharField(max_length=42, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('address', models.CharField(max_length=42, verbose_name='Address')),
                ('date_signed_in', models.DateField(verbose_name='Date signed in')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('content_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/videos'), upload_to='')),
                ('medium_time_watching', models.PositiveIntegerField()),
                ('count_of_watches', models.IntegerField()),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='api.blogger')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advertiser')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blogger')),
            ],
        ),
    ]
