# Generated by Django 4.0.4 on 2022-05-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_platformuser_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformaction',
            name='tx',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
