# Generated by Django 4.0.4 on 2022-05-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_advertisement_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactorParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
